# Generated by Django 5.2.7 on 2025-10-28 22:58

import accounts.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('rol', models.CharField(choices=[('STUDENT', 'Estudiante'), ('REVIEWER', 'Revisor'), ('ADMIN', 'Admin')], db_index=True, default='STUDENT', max_length=10)),
                ('rut', models.CharField(blank=True, max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='StudentFicha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_global', models.CharField(choices=[('DRAFT', 'Borrador'), ('ENVIADA', 'Enviada por estudiante'), ('EN_REVISION', 'En revisión'), ('OBSERVADA', 'Observada'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], db_index=True, default='DRAFT', max_length=20)),
                ('observaciones_globales', models.TextField(blank=True, null=True)),
                ('revisado_en', models.DateTimeField(blank=True, null=True)),
                ('pdf_resultado_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_revisadas', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_ficha',
            },
        ),
        migrations.CreateModel(
            name='StudentDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, choices=[('GENERALES', 'Antecedentes Generales'), ('ACADEMICOS', 'Antecedentes Académicos'), ('MORBIDOS', 'Antecedentes Mórbidos'), ('VACUNAS', 'Vacunas / Serología'), ('ADJUNTA', 'Documentación Adjunta')], db_index=True, max_length=15, null=True)),
                ('item', models.CharField(blank=True, choices=[('CI_FRENTE', 'CI (frente)'), ('CI_REVERSO', 'CI (reverso)'), ('AUTORIZACION_MEDICA', 'Autorización médica práctica'), ('HEPB_CERT', 'Cert. Hepatitis B'), ('VARICELA_IGG', 'Serología Varicela (IgG)'), ('INFLUENZA_CERT', 'Cert. Influenza'), ('SARS_COV_2_MEVACUNO', 'Cert. MeVacuno (SARS-CoV-2)'), ('CURSO_INTRO_COVID', 'Curso Introducción COVID (OMS)'), ('CURSO_EPP', 'Curso EPP'), ('CURSO_IAAS', 'Curso IAAS (OMS)'), ('CURSO_RCP_BLS', 'Curso RCP/BLS'), ('INDUCCION_CC', 'Inducción Campo Clínico (SS Biobío)'), ('ALERGIAS_CERT', 'Certificado Alergias'), ('ENFERMEDADES_CERT', 'Certificado Enfermedades'), ('MEDICAMENTOS_CERT', 'Certificado Medicamentos'), ('OTROS_ANTECEDENTES_CERT', 'Certificado Otros Antecedentes')], db_index=True, max_length=30, null=True)),
                ('file', models.FileField(blank=True, max_length=500, null=True, upload_to=accounts.models.student_upload_path)),
                ('file_name', models.CharField(max_length=255)),
                ('file_mime', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('review_status', models.CharField(choices=[('ADJUNTADO', 'Adjuntado'), ('REVISADO_NO_OK', 'Revisado no ok'), ('REVISADO_OK', 'Revisado ok')], db_index=True, default='ADJUNTADO', max_length=20)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docs_revisados', to=settings.AUTH_USER_MODEL)),
                ('ficha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.studentficha')),
            ],
            options={
                'db_table': 'student_documents',
            },
        ),
        migrations.CreateModel(
            name='StudentDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estudiante', models.CharField(max_length=120)),
                ('rut', models.CharField(db_index=True, max_length=20)),
                ('firma', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('ficha', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='declaracion', to='accounts.studentficha')),
            ],
            options={
                'db_table': 'student_declaration',
            },
        ),
        migrations.CreateModel(
            name='StudentAcademic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_social', models.CharField(blank=True, max_length=120, null=True)),
                ('carrera', models.CharField(blank=True, max_length=120, null=True)),
                ('anio_cursa', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('asignatura', models.CharField(blank=True, max_length=160, null=True)),
                ('correo_institucional', models.EmailField(blank=True, max_length=254, null=True)),
                ('correo_personal', models.EmailField(blank=True, max_length=254, null=True)),
                ('ficha', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academicos', to='accounts.studentficha')),
            ],
            options={
                'db_table': 'student_academic',
            },
        ),
        migrations.CreateModel(
            name='SerologyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathogen', models.CharField(choices=[('COVID_19', 'COVID-19'), ('HEPATITIS_B', 'Hepatitis B'), ('VARICELA', 'Varicela'), ('INFLUENZA', 'Influenza')], db_index=True, max_length=20)),
                ('result', models.CharField(choices=[('POSITIVA', 'Positiva'), ('NEGATIVA', 'Negativa'), ('INDETERMINADA', 'Indeterminada')], max_length=15)),
                ('date', models.DateField()),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serologies', to='accounts.studentficha')),
            ],
            options={
                'db_table': 'student_serology_result',
            },
        ),
        migrations.CreateModel(
            name='StudentGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_legal', models.CharField(blank=True, max_length=120, null=True)),
                ('rut', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('genero', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono_celular', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion_actual', models.TextField(blank=True, null=True)),
                ('direccion_origen', models.TextField(blank=True, null=True)),
                ('contacto_emergencia_nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('contacto_emergencia_parentesco', models.CharField(blank=True, max_length=80, null=True)),
                ('contacto_emergencia_telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('centro_salud', models.CharField(blank=True, max_length=120, null=True)),
                ('seguro', models.CharField(blank=True, choices=[('FONASA_A', 'FONASA A'), ('FONASA_B', 'FONASA B'), ('FONASA_C', 'FONASA C'), ('FONASA_D', 'FONASA D'), ('ISAPRE', 'ISAPRE'), ('FUERZAS_ARMADAS', 'Fuerzas Armadas'), ('OTRO', 'Otro')], max_length=20, null=True)),
                ('seguro_detalle', models.CharField(blank=True, max_length=120, null=True)),
                ('foto_ficha', models.ImageField(blank=True, help_text='Solo PNG', null=True, upload_to=accounts.models.general_png_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'])])),
                ('ficha', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generales', to='accounts.studentficha')),
            ],
            options={
                'db_table': 'student_general',
            },
        ),
        migrations.CreateModel(
            name='StudentGeneralPhotoBlob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mime', models.CharField(default='image/png', max_length=100)),
                ('data', models.BinaryField()),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('general', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo_blob', to='accounts.studentgeneral')),
            ],
            options={
                'db_table': 'student_general_photo_blob',
            },
        ),
        migrations.CreateModel(
            name='StudentMedicalBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alergias_detalle', models.TextField(blank=True, null=True)),
                ('grupo_sanguineo', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True)),
                ('cronicas_detalle', models.TextField(blank=True, null=True)),
                ('medicamentos_detalle', models.TextField(blank=True, null=True)),
                ('otros_antecedentes', models.TextField(blank=True, null=True)),
                ('ficha', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicos', to='accounts.studentficha')),
            ],
            options={
                'db_table': 'student_medical_background',
            },
        ),
        migrations.CreateModel(
            name='VaccineDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_type', models.CharField(choices=[('COVID_19', 'COVID-19'), ('HEPATITIS_B', 'Hepatitis B'), ('VARICELA', 'Varicela'), ('INFLUENZA', 'Influenza')], db_index=True, max_length=20)),
                ('dose_label', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_doses', to='accounts.studentficha')),
            ],
            options={
                'db_table': 'student_vaccine_dose',
            },
        ),
        migrations.CreateModel(
            name='StudentDocumentBlob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_backend', models.CharField(choices=[('FILE', 'File storage (MEDIA/S3)'), ('DB', 'Database blob')], db_index=True, default='DB', max_length=8)),
                ('data', models.BinaryField(blank=True, null=True)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blob', to='accounts.studentdocuments')),
            ],
            options={
                'db_table': 'student_document_blob',
                'indexes': [models.Index(fields=['storage_backend'], name='idx_blob_backend'), models.Index(fields=['sha256'], name='idx_blob_sha256')],
            },
        ),
        migrations.CreateModel(
            name='DocumentReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('ADJUNTADO', 'Adjuntado'), ('REVISADO_NO_OK', 'Revisado no ok'), ('REVISADO_OK', 'Revisado ok')], max_length=20, null=True)),
                ('new_status', models.CharField(choices=[('ADJUNTADO', 'Adjuntado'), ('REVISADO_NO_OK', 'Revisado no ok'), ('REVISADO_OK', 'Revisado ok')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='accounts.studentdocuments')),
            ],
            options={
                'db_table': 'student_document_review_log',
                'indexes': [models.Index(fields=['document', 'reviewed_at'], name='idx_doclog_doc_time')],
            },
        ),
        migrations.AddIndex(
            model_name='studentficha',
            index=models.Index(fields=['user', 'estado_global'], name='idx_ficha_user_estado'),
        ),
        migrations.AddIndex(
            model_name='studentdocuments',
            index=models.Index(fields=['ficha', 'section', 'item'], name='idx_doc_ficha_section_item'),
        ),
        migrations.AddIndex(
            model_name='studentdocuments',
            index=models.Index(fields=['review_status'], name='idx_doc_review_status'),
        ),
        migrations.AddIndex(
            model_name='serologyresult',
            index=models.Index(fields=['ficha', 'pathogen'], name='idx_sero_ficha_pathogen'),
        ),
        migrations.AddIndex(
            model_name='studentgeneralphotoblob',
            index=models.Index(fields=['sha256'], name='idx_genphotoblob_sha256'),
        ),
        migrations.AddIndex(
            model_name='vaccinedose',
            index=models.Index(fields=['ficha', 'vaccine_type'], name='idx_vax_ficha_type'),
        ),
    ]
