# Generated by Django 5.2.7 on 2025-10-29 07:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_photoblob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdocuments',
            name='item',
            field=models.CharField(blank=True, choices=[('CI_FRENTE', 'CI (frente)'), ('CI_REVERSO', 'CI (reverso)'), ('AUTORIZACION_MEDICA', 'Autorización médica práctica'), ('CERT_ALUMNO_REGULAR', 'Certificado de Alumno Regular'), ('HEPB_CERT', 'Cert. Hepatitis B'), ('VARICELA_IGG', 'Serología Varicela (IgG)'), ('INFLUENZA_CERT', 'Cert. Influenza'), ('SARS_COV_2_MEVACUNO', 'Cert. MeVacuno (SARS-CoV-2)'), ('CURSO_INTRO_COVID', 'Curso Introducción COVID (OMS)'), ('CURSO_EPP', 'Curso EPP'), ('CURSO_IAAS', 'Curso IAAS (OMS)'), ('CURSO_RCP_BLS', 'Curso RCP/BLS'), ('INDUCCION_CC', 'Inducción Campo Clínico (SS Biobío)'), ('ALERGIAS_CERT', 'Certificado Alergias'), ('ENFERMEDADES_CERT', 'Certificado Enfermedades'), ('MEDICAMENTOS_CERT', 'Certificado Medicamentos'), ('OTROS_ANTECEDENTES_CERT', 'Certificado Otros Antecedentes')], db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='studentgeneralphotoblob',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
