# Generated by Django 5.2.7 on 2025-10-28 03:48

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_foto_ficha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentficha',
            name='foto',
        ),
        migrations.AddField(
            model_name='studentgeneral',
            name='foto_ficha',
            field=models.ImageField(blank=True, help_text='Solo PNG', null=True, upload_to=accounts.models.general_png_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'])]),
        ),
    ]
