# Generated by Django 5.2.7 on 2025-11-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_cert_alumno_regular'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentficha',
            name='is_activa',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='studentficha',
            index=models.Index(fields=['user', 'is_activa'], name='idx_ficha_user_activa'),
        ),
        migrations.AddConstraint(
            model_name='studentficha',
            constraint=models.UniqueConstraint(condition=models.Q(('is_activa', True)), fields=('user',), name='uniq_ficha_activa_por_usuario'),
        ),
    ]
