# Generated by Django 5.2.7 on 2025-11-10 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_comentariodocumento'),
        ('accounts', '0004_studentficha_is_activa_and_more'),
    ]

    operations = [
    ]
