# Generated by Django 5.2.7 on 2025-11-11 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20251110_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioFicha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_ficha', to='accounts.studentficha')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFieldReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(db_index=True, max_length=80)),
                ('field_key', models.CharField(db_index=True, max_length=120)),
                ('status', models.CharField(choices=[('REVISADO_OK', 'Revisado OK'), ('REVISADO_NO_OK', 'Revisado NO OK')], db_index=True, max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_reviews', to='accounts.studentficha')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_reviews_done', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_field_review',
                'indexes': [models.Index(fields=['ficha', 'field_key'], name='idx_field_ficha_key'), models.Index(fields=['ficha', 'status'], name='idx_field_ficha_status')],
                'unique_together': {('ficha', 'field_key')},
            },
        ),
    ]
