# Generated by Django 5.2.7 on 2025-11-17 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_comentarioficha_studentfieldreview'),
    ]

    operations = [
        # OJO: Quitamos estos dos AddField porque las columnas ya existen en la BD
        # migrations.AddField(
        #     model_name='comentariodocumento',
        #     name='order',
        #     field=models.IntegerField(db_index=True, default=0),
        # ),
        # migrations.AddField(
        #     model_name='studentdocuments',
        #     name='order',
        #     field=models.IntegerField(db_index=True, default=0),
        # ),

        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_consulta', models.CharField(max_length=80)),
                ('asunto', models.CharField(max_length=200)),
                ('detalle', models.TextField()),
                ('estado', models.CharField(choices=[('NUEVA', 'Nueva'), ('EN_PROCESO', 'En proceso'), ('CERRADA', 'Cerrada')], default='NUEVA', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
