# Generated by Django 5.2.7 on 2025-11-17 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_comentariodocumento_order_studentdocuments_order_and_more'),
    ]

    operations = [
        # IMPORTANTE:
        # Quitamos los AddField de 'order' porque esas columnas
        # ya fueron creadas en la migración 0007 y ya existen en la BD.

        migrations.AlterField(
            model_name='supportticket',
            name='tipo_consulta',
            field=models.CharField(
                choices=[
                    ('Duda sobre ficha', 'Duda sobre ficha'),
                    ('Problema al subir certificado', 'Problema al subir certificado'),
                    ('Actualización de datos', 'Actualización de datos'),
                    ('Otra consulta', 'Otra consulta'),
                ],
                max_length=80,
            ),
        ),
    ]
