# Generated by Django 5.2.7 on 2025-11-17 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_comentariodocumento_order_studentdocuments_order_and_more"),
    ]

    # OJO:
    # Dejamos esta migración SIN operaciones de AddField,
    # porque las columnas 'order' ya existen en la base de datos.
    operations = [
        # No-op: esta migración solo sirve para avanzar el historial.
    ]
