# Generated by Django 5.2.8 on 2025-11-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_comentariodocumento_order_studentdocuments_order'),
    ]

    operations = [
        # ⚠️ OJO: ya NO agregamos más los campos "order"
        # en ComentarioDocumento ni StudentDocuments porque
        # ya existen en la BD desde la migración 0009.

        migrations.AddField(
            model_name='supportticket',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='respuesta_admin',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='estado',
            field=models.CharField(
                choices=[('NUEVA', 'Nueva'), ('CERRADA', 'Cerrada')],
                default='NUEVA',
                max_length=20,
            ),
        ),
    ]
