# Generated by Django 5.2.8 on 2025-11-19 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_comentariodocumento_order_studentdocuments_order_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentAcademic',
            new_name='StudentAcademicos',
        ),
        migrations.RenameModel(
            old_name='StudentDeclaration',
            new_name='StudentDeclaracion',
        ),
        migrations.RenameModel(
            old_name='StudentGeneral',
            new_name='StudentGenerales',
        ),
        migrations.RenameModel(
            old_name='StudentMedicalBackground',
            new_name='StudentMedicos',
        ),

        # ⚠️ Ya quitamos el RemoveField de SupportTicket.user porque fallaba
        # migrations.RemoveField(
        #     model_name='supportticket',
        #     name='user',
        # ),

        migrations.AlterField(
            model_name='studentficha',
            name='estado_global',
            field=models.CharField(
                choices=[
                    ('OK', 'OK'),
                    ('DRAFT', 'Borrador'),
                    ('ENVIADA', 'Enviada por estudiante'),
                    ('EN_REVISION', 'En revisión'),
                    ('OBSERVADA', 'Observada'),
                    ('APROBADA', 'Aprobada'),
                    ('RECHAZADA', 'Rechazada'),
                ],
                db_index=True,
                default='DRAFT',
                max_length=20,
            ),
        ),

        # 🔹 PRIMERO borramos el modelo/vieja tabla student_field_review
        migrations.DeleteModel(
            name='StudentFieldReview',
        ),

        # 🔹 LUEGO creamos la nueva tabla FieldReview con el mismo db_table
        migrations.CreateModel(
            name='FieldReview',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'section',
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default='',
                        max_length=80,
                    ),
                ),
                (
                    'field_key',
                    models.CharField(
                        db_index=True,
                        max_length=120,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[('OK', 'OK'), ('OBSERVADO', 'Observado')],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ('notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                (
                    'ficha',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='field_reviews',
                        to='accounts.studentficha',
                    ),
                ),
                (
                    'reviewed_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='field_reviews_done',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'student_field_review',
            },
        ),

        migrations.CreateModel(
            name='StudentSupportTicket',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('tipo_consulta', models.CharField(max_length=100)),
                ('asunto', models.CharField(max_length=200)),
                ('detalle', models.TextField()),
                ('respuesta_admin', models.TextField(blank=True, null=True)),
                (
                    'estado',
                    models.CharField(
                        choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')],
                        db_index=True,
                        default='ABIERTO',
                        max_length=20,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'ficha',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='support_tickets',
                        to='accounts.studentficha',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='support_tickets',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'student_support_ticket',
            },
        ),

        migrations.DeleteModel(
            name='SupportTicket',
        ),

        migrations.AddIndex(
            model_name='fieldreview',
            index=models.Index(
                fields=['ficha', 'field_key'],
                name='idx_field_ficha_key',
            ),
        ),
        migrations.AddIndex(
            model_name='fieldreview',
            index=models.Index(
                fields=['ficha', 'status'],
                name='idx_field_ficha_status',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='fieldreview',
            unique_together={('ficha', 'field_key')},
        ),
        migrations.AddIndex(
            model_name='studentsupportticket',
            index=models.Index(
                fields=['estado', 'created_at'],
                name='idx_ticket_estado_created',
            ),
        ),
    ]
