# Generated by Django 5.2.8 on 2025-11-19 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_studentacademic_studentacademicos_and_more'),
    ]

    operations = [
        # Renombrar modelos antiguos a los nuevos nombres
        migrations.RenameModel(
            old_name='StudentAcademicos',
            new_name='StudentAcademic',
        ),
        migrations.RenameModel(
            old_name='StudentDeclaracion',
            new_name='StudentDeclaration',
        ),
        migrations.RenameModel(
            old_name='StudentGenerales',
            new_name='StudentGeneral',
        ),
        migrations.RenameModel(
            old_name='StudentMedicos',
            new_name='StudentMedicalBackground',
        ),

        # ⚠️ Estos campos en StudentSupportTicket ya NO existen en la BD real,
        # así que solo actualizamos el estado de Django, sin tocar la tabla.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='studentsupportticket',
                    name='ficha',
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='studentsupportticket',
                    name='user',
                ),
            ],
            database_operations=[],
        ),

        # ⚠️ Las columnas "order" ya existen en la BD, así que otra vez:
        # solo cambiamos el estado de Django.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='comentariodocumento',
                    name='order',
                    field=models.IntegerField(default=0, db_index=True),
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='studentdocuments',
                    name='order',
                    field=models.IntegerField(default=0, db_index=True),
                ),
            ],
            database_operations=[],
        ),

        # ⚠️ La tabla student_field_review YA existe en BD.
        # Usamos SeparateDatabaseAndState para NO crearla de nuevo.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='StudentFieldReview',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('section', models.CharField(db_index=True, max_length=80)),
                        ('field_key', models.CharField(db_index=True, max_length=120)),
                        (
                            'status',
                            models.CharField(
                                choices=[('REVISADO_OK', 'Revisado OK'), ('REVISADO_NO_OK', 'Revisado NO OK')],
                                db_index=True,
                                max_length=20,
                            ),
                        ),
                        ('notes', models.TextField(blank=True, null=True)),
                        ('reviewed_at', models.DateTimeField(auto_now=True)),
                        (
                            'ficha',
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name='field_reviews',
                                to='accounts.studentficha',
                            ),
                        ),
                        (
                            'reviewed_by',
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name='field_reviews_done',
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        'db_table': 'student_field_review',
                    },
                ),
            ],
            database_operations=[],
        ),

        # SupportTicket SÍ lo queremos crear en BD (esa tabla no existe aún)
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'tipo_consulta',
                    models.CharField(
                        choices=[
                            ('Duda sobre ficha', 'Duda sobre ficha'),
                            ('Problema al subir certificado', 'Problema al subir certificado'),
                            ('Actualización de datos', 'Actualización de datos'),
                            ('Otra consulta', 'Otra consulta'),
                        ],
                        max_length=80,
                    ),
                ),
                ('asunto', models.CharField(max_length=200)),
                ('detalle', models.TextField()),
                ('respuesta_admin', models.TextField(blank=True)),
                (
                    'estado',
                    models.CharField(
                        choices=[('NUEVA', 'Nueva'), ('CERRADA', 'Cerrada')],
                        default='NUEVA',
                        max_length=20,
                    ),
                ),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='support_tickets',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),

        # Eliminar modelos antiguos
        migrations.DeleteModel(
            name='FieldReview',
        ),
        migrations.DeleteModel(
            name='StudentSupportTicket',
        ),

        # Índices y unique_together de StudentFieldReview:
        # también solo en el estado de Django, por si en BD ya existen.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name='studentfieldreview',
                    index=models.Index(fields=['ficha', 'field_key'], name='idx_field_ficha_key'),
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name='studentfieldreview',
                    index=models.Index(fields=['ficha', 'status'], name='idx_field_ficha_status'),
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='studentfieldreview',
                    unique_together={('ficha', 'field_key')},
                ),
            ],
            database_operations=[],
        ),
    ]
